stages:
  - test
  - build
  - scan
  - publish
  - deploy
  - merge

variables:
  DOCKER_IMAGE: "dulno-core-base"
  DOCKER_DOCS_IMAGE: "dulno-core-base-docs"

include:
  - project: 'dulno/dulno-template'
    file: '/core/core-template.yml'

build_jar:
  stage: build
  image: gradle:9.2.0-jdk21
  script:
    - gradle bootJar
  artifacts:
    paths:
      - build/libs/
    expire_in: 1 day

build_geo:
  stage: build
  image: gradle:9.2.0-jdk21
  script:
    - gradle downloadGeoLite2Database
  artifacts:
    paths:
      - geo/
    expire_in: 1 day

publish_gradle:
  stage: publish
  image: gradle:9.2.0-jdk21
  dependencies: []
  script:
    - gradle publish