stages:
  - test
  - build
  - scan
  - publish
  - deploy
  - merge

variables:
  DOCKER_IMAGE: "dulno-core-base"
  DOCKER_DOCS_IMAGE: "dulno-core-base-docs"

include:
  - project: 'dulno/dulno-template'
    file: '/core/core-template.yml'